language: java
jdk:
  - oraclejdk8
#after_success:
#  - mvn clean cobertura:cobertura coveralls:report
before_deploy:
  - export MY_FILE_PATH=$(ls target/dubbo-switch-*.jar)
deploy:
  provider: releases
  api_key: $github_release_token
  file: "${MY_FILE_PATH}"
  skip_cleanup: true
  on:
    tags: true