language: java
jdk:
  - oraclejdk8
#after_success:
#  - mvn clean cobertura:cobertura coveralls:report
deploy:
  provider: releases
  api_key: $github_release_token
  file: $HOME/build/xburning/dubbo-switch/target/dubbo-switch-*.jar
  skip_cleanup: true
  overwrite: true
#  on:
#     tags: true